datasource/configdrive/configdrive.go
datasource/configdrive/configdrive_test.go

This was lost in some of the recent refactoring.

configdrive: check metadata length before parsing

---

config/validate/rules.go
config/validate/rules_test.go

The validation of the encoding for write_files was looking for a node named "contents" when the node name is "content."

Fix typo, "contents" should be "content"

---

datasource/metadata/cloudsigma/server_context.go
datasource/metadata/cloudsigma/server_context_test.go

Even when public ssh key is not set by the user, CloudSigma's server
context has a key `meta.ssh_public_key` which is just an empty string.
So instead of just relying on the "comma ok" idiom I make sure the value
is not an empty string.

Make sure public ssh key is not empty from CloudSigma's server context

---

Documentation/cloud-config.md
config/config_test.go
config/user.go
system/user.go

This adds support for specifying the login shell of created users.

config/system: add shell user attribute

---

Documentation/cloud-config.md
config/config.go
config/etcd.go
config/etcd2.go
config/validate/rules.go
config/validate/rules_test.go
initialize/config.go
system/etcd2.go

This fixes https://github.com/coreos/coreos-cloudinit/issues/329.
The list of deprecated options comes from https://github.com/coreos/coreos-cloudinit/pull/313.
Doing a little more testing...

config: add support for etcd2

---

.travis.yml

Removing 1.2 and 1.3 from TravisCI testing.

Go ci versions

---

network/interface.go
network/interface_test.go

Bond options aren't persisted to the files. This isn't a problem if you're relying on the network portions of coreos-cloudinit for every boot. Because the calls are made directly to configure the interface. 
However, the generated files didn't have the bond config in them. This meant that the .netdev file was largely incorrect.  This fixes that but might be better handled in a different options array.

Bond options persisted to the generated netdev file.

---

Documentation/cloud-config.md
config/flannel.go

Related with coreos/flannel#259
This will allow users to use flannel under a **NAT** environment easily, by just setting `public_ip: $public_ipv4` on their `cloud-config`.
Example:
```
#cloud-config
coreos:
flannel:
public-ip: $public_ipv4
```

Add PublicIP option on flannel

---

Documentation/vmware-backdoor.md
datasource/vmware/vmware.go
datasource/vmware/vmware_test.go

allow use of a URL instead of an inline document.
Inline document takes precedence.

datasource/vmware: introduce guestinfo.coreos.config.url

---

config/config.go
initialize/user_data_test.go

If cloud-config contains trailing whitespaces in the header - coreos-cloudinit will fail that config. Example has trailing whitespace and you can not see it:
```
#cloud-config 
```
/cc @robszumski 
/cc @crawford

Trim trailing whitespaces in #cloud-config header

---

Documentation/cloud-config-oem.md
Documentation/cloud-config.md

I realize this is one of the selling points of YAML, but it causes far
too much confusion. Turns out typing is a good thing.
Fixes https://github.com/coreos/coreos-cloudinit/issues/316.

docs: quote everything

---

coreos-cloudinit.go

We still utilize the network code on first boot, so it should remain until we implement ignition, but we don't want it on subsequent boots, which is what this line would do.

cloudinit: Removing convert-netconf from Packet OEM

---

datasource/metadata/digitalocean/metadata.go
network/digitalocean.go
network/digitalocean_test.go

First pass at allowing CoreOS droplets on DigitalOcean to parse their "anchor IP" which is used to rewrite traffic from a floating IP into the droplet.
The intent here is to add a second IPv4 address to the primary network interface.  I've updated the tests to reflect this as well.  Please let me know if I'm doing anything incorrectly, and thanks for your time.
/cc @crawford

datasource, network: add support for DigitalOcean floating IPs

---

config/etcd2.go

In etcd 2.2 release, we introduced a new flag called `walDir`.
See https://github.com/coreos/etcd/blob/release-2.2/Documentation/configuration.md#-wal-dir for more details.

config: add wal_dir into etcd2.go

---

network/digitalocean.go
network/digitalocean_test.go

Fixes issue where containers are unable to reach the network due to multiple gateways.  Tested and confirmed working on our platform.
```
core@core ~ $ ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
link/ether 04:01:80:ba:e5:01 brd ff:ff:ff:ff:ff:ff
inet 169.254.57.197/16 brd 169.254.255.255 scope link eth0
valid_lft forever preferred_lft forever
inet 159.203.20.240/20 brd 159.203.31.255 scope global eth0
valid_lft forever preferred_lft forever
inet 10.20.0.5/16 brd 10.20.255.255 scope global eth0
valid_lft forever preferred_lft forever
inet6 fe80::601:80ff:feba:e501/64 scope link 
valid_lft forever preferred_lft forever
core@core ~ $ ip route
default via 159.203.16.1 dev eth0  proto static 
default dev eth0  proto …
```

network: do not assign gateway for DigitalOcean anchor IP address

---

Documentation/cloud-config-locations.md
Documentation/vmware-guestinfo.md
coreos-cloudinit.go

(Proposed) Based on results of google searches on a few possible titles
to improve on the connotation of backdoor, Guestinfo
Interface (part of the RPC API) seems recognizable in vmware
circles.
The flag to cloudinit changes with this to
`-from-vmware-guestinfo`.

Docs/vmware-backdoor: Rename backdoor to guestinfo

---

Documentation/cloud-config.md

Rather than link to specific blob hashes, now that things have been synced to 0.4.9 we can link to the 0.4 release for original etcd; also fixes a link that was to a blob hash of configuration.md instead of the head of master for etcd.

docs: fix links to specific blobs

---

Documentation/vmware-guestinfo.md
coreos-cloudinit.go

In line with https://github.com/coreos/docs/issues/650,
revert a little bit of https://github.com/coreos/coreos-cloudinit/pull/404
to document `--longoption` with two hyphens in document and Usage.

Vmware-guestinfo: Double hyphen long options.

---

coreos-cloudinit.go
coreos-cloudinit_test.go
test

The cloud-init project uses a similar technique to natively support gzipped user-data. The alternative path would be to use a script that decompresses the user data and then calls into cloudinit, but this seemed simple enough to bring into cloudinit itself.
And, unrelated, but in the same commit – without the change to `test`, I found that the top-level tests in coreos-cloudinit_test.go were not running.

gzip autodetection

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/sigma/vmw-ovflib/README
Godeps/_workspace/src/github.com/sigma/vmw-ovflib/ovf.go
Godeps/_workspace/src/github.com/sigma/vmw-ovflib/ovf_test.go
coreos-cloudinit.go
datasource/vmware/vmware.go
datasource/vmware/vmware_test.go
units/90-ovfenv.rules
units/media-ovfenv.mount
units/user-config-ovfenv.service
units/user-config.target

If an OVF environment is present (either through VMware backdoor, or as a
mounted cdrom), use it to extract user/meta data.

datasource/vmware: add support for reading from OVF environment

---

units/user-cloudinit-proc-cmdline.service
units/user-cloudinit@.service

This fix user-cloudinit-proc-cmdline.service being run at the same time as system-cloudinit@usr-share-oem-cloud\x2dconfig.yml.service on launch time.

Add After=system-config.target for user-cloudinit*

---

Documentation/cloud-config.md

{{site.url}} was not working properly.  Also clean up wording of cloud-config validation.

cloud-config.md: Minor cleanup of validation text

---

units/user-config.target

This unit doesn't actually exist. user-config-ovfenv.service is triggered by
media-ovfenv.mount so we don't need the path anyway.

units: remove user-config-ovfenv.path

---

units/90-configdrive.rules

CDROM media or ISO image might also contain UDF (ISO/IEC 13346) file system which should be support as well.

add support for media/images with UDF filesystem

---

config/config.go
config/config_test.go
initialize/user_data.go
system/file.go
system/file_test.go

Decoding of a gzipped cloud init template is already supported, but when it comes to write-files if  the content is encoded with a some format, decode operation does not applied to them. Currently only write-files section support encoding type, so do the transformation while initializing the cloud init template.
WriteFile also does the transformation if the encoding type is set. CloudConfig.Decode unsets it.

config: add decoding support for cloud init template write_files section

---

units/system-cloudinit@.service
units/user-cloudinit-proc-cmdline.service
units/user-cloudinit@.service
units/user-config-ovfenv.service
units/user-configdrive.service
units/user-configvirtfs.service

Since coreos-cloudinit's internal service scheduling is opaque to
systemd and doesn't handle dependency-loop detection, it is possible for
it to cause deadlocks. Introducing the timeout to all invocations
provides a mechanism for system to regain control of the startup
sequence.

units: add timeout to all services

---

build

build: fix missing = in GLDFLAGS
The -X option requires = rather than space.

build: fix missing = in GLDFLAGS

---

Documentation/cloud-config.md
config/flannel.go
config/fleet.go
config/locksmith.go

expose username and password configuration options for flannel, fleet, and locksmith to etcd
Addresses https://github.com/coreos/flannel/issues/419 and https://github.com/coreos/fleet/issues/1505

config: add etcd authentication

---

Documentation/cloud-config.md

Hi,
Just a minor documentation fix for a piece of inline code that wasn't marked as such.

docs: add verbatim syntax to cloud-config header

---

Documentation/cloud-config-examples.md

The coreos/docs repo was recently modified to replace all cloud config
examples with CLCs. This commit adds many of the removed examples to
this repo.

Documentation: add common examples that were removed from coreos/docs

---

Documentation/debian-interfaces.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

Documentation/cloud-config.md
config/config.go
config/validate/rules_test.go

etcd2 will be removed from Container Linux in early 2018.

docs: deprecate etcd2 config section

---

Documentation/cloud-config.md
config/update.go
config/update_test.go
pkg/http_client_test.go
system/update_test.go

Removes all mention of the "best effort" locksmith strategy from documentation, tests, and strategies accepted during validation.
Fixes https://github.com/coreos/coreos-cloudinit/pull/451

*: remove locksmith "best effort" strategy
